- name: allow established and related connections
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: allow icmp
  iptables:
    chain: INPUT
    protocol: icmp
    jump: ACCEPT

- name: allow loopback
  iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT

- name: add tcp ports
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item }}"
    ctstate: NEW
    jump: ACCEPT
  loop:
    - "80"
    - "443"
    - "22"
    - "53"

- name: Set the policy for the input chain to drop
  iptables:
    chain: INPUT
    policy: DROP


  
  
