- name: install nginx and apache
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - nginx
    - httpd

- name: ensure the default apache port is 8080
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^Listen '
    insertafter: '^#Listen '
    line: Listen 8080

- name: start and enable nginx and httpd
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - nginx
    - httpd

- name: copy nginx.conf
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root

- name: copy reverse proxy configuration files to conf.d
  template:
    src: balance.conf
    dest: /etc/nginx/conf.d/balance.conf
    owner: root
    group: root

- name: copy configuration files for apache as backend server
  template:
    src: servers.conf
    dest: /etc/httpd/conf.d/servers.conf
    owner: root
    group: root

- name: copy default index pages in apache web servers
  copy:
    src: www/
    dest: /var/www/
    owner: root
    group: root
    directory_mode: yes

- name: create access_log and error_log files for apache web servers
  copy:
    src: httpd/
    dest: /var/log/httpd/
    owner: root
    group: root
    directory_mode: yes

- name: restart services
  service:
    name: "{{ item }}"
    state: restarted
  loop:
      - nginx
      - httpd

